# Generated by Django 2.2.12 on 2020-04-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='home.Partner'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='home.Partner'),
        ),
    ]
