# Generated by Django 2.2.12 on 2020-04-30 16:30

from django.db import migrations, models
import django.utils.timezone
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_event_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('reference', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AddField(
            model_name='event',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Percentage Discount'),
        ),
        migrations.AddField(
            model_name='event',
            name='ends_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='starts_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount in UGX'),
        ),
    ]
