# Generated by Django 2.2.12 on 2020-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200502_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_effected',
            field=models.BooleanField(default=False),
        ),
    ]
